name 'elasticsearch'
maintainer 'Heavy Water Operations, LLC.'
maintainer_email 'helpdesk@heavywater.io'
license 'apachev2'
description 'Simple LWRP for elasticsearch instances and configuration.'
version '0.1.2'
